### ISSUE TITLE
Does this mean that we can use this csharp client program in the client machine without installing python in it?

### ISSUE THREAD

**Issue by R-Miner** [Wertugo/TensorFlowServingCSharpClient#1]

**Comment by iminakov** [comment]
That's right. C# client uses gRPC communication protocol to access to TensorFlowServicing.
So in my example I use C# with Windows 10 and TensorFlow Service on Linux Ubuntu.

**Comment by R-Miner** [comment]
@Wertugo 
Thankyou very much for your response. Its of great help.

I have two more questions out of curiosity.

1.Can we have a **windows machine as **server** with python and tensorflow serving installed in it?
2. Is it possible to do tensorflow serving without installing python on windows  server machine at all? I don't think so, but would appreciate your response.

It might be very stupid of me asking such questions. I felt that it doesn't hurt anyone to make sure of some things.

Thanks  in advance.
